/**
 * Filesystem-style content for the terminal portfolio.
 * Lines use a tiny DSL: "line:<color-class>|<text>".
 *   - color-class: "", "c", "y", "g", "b", "m", "r", "o", "w", "dim", "faint"
 *   - special inline: "skill:Name:percent"  → rendered as a phosphor bar
 *   - special inline: "link|<url>|<label>" or "link|<url>"
 */

export type FsNode =
  | { type: 'dir'; children: string[] }
  | { type: 'file'; kind: 'md' | 'exe'; meta?: string; body: () => string[] };

export const FS: Record<string, FsNode> = {
  '/': {
    type: 'dir',
    children: [
      'README.md',
      'whoami',
      'about/',
      'education/',
      'experience/',
      'projects/',
      'publications/',
      'skills/',
      'contact/',
    ],
  },

  '/README.md': {
    type: 'file',
    kind: 'md',
    meta: 'welcome',
    body: () => [
      'line:c|# michal-borek/portfolio',
      'line:|',
      'line:|Most portfolios are landing pages. Mine boots.',
      'line:|',
      'line:dim|## getting around',
      'line:|',
      'line:|  ls                  list a directory',
      'line:|  cd <dir>            change directory',
      'line:|  cat <file>          read a file',
      'line:|  tree                show everything at once',
      'line:|  whoami              one-liner about me',
      'line:|  help                full command list',
      'line:|',
      'line:dim|## quick start',
      'line:|',
      'line:|  cd about && cat me.md          who I am',
      'line:|  cd projects && ls              what I have shipped',
      'line:|  cat contact/info               how to reach me',
      'line:|',
      'line:dim|## prefer a document?',
      'line:|',
      'line:|  tap the "Document" toggle in the top-right corner.',
    ],
  },

  '/whoami': {
    type: 'file',
    kind: 'exe',
    meta: 'bio',
    body: () => [
      'line:w|Michal Borek',
      'line:dim|ML Engineer · AI Consultant · Researcher',
      'line:dim|MSU · Spring 2026 · East Lansing, MI · open to any US state',
    ],
  },

  '/about': { type: 'dir', children: ['me.md', 'looking-for.md'] },
  '/about/me.md': {
    type: 'file',
    kind: 'md',
    meta: 'bio',
    body: () => [
      'line:c|# Michal Borek',
      'line:|Machine Learning Engineer · AI Consultant · Researcher',
      'line:|',
      'line:|I build production ML systems — from RAG pipelines and LLM',
      'line:|applications to computer-vision models. Comfortable across',
      'line:|the whole stack: training, evaluation, the backend that',
      'line:|serves it, and the frontend that demos it.',
      'line:|',
      'line:|Finishing my B.S. in Computational Data Science at',
      'line:|Michigan State, graduating Spring 2026. Mathematics minor.',
      'line:|Two peer-reviewed publications on the wall.',
      'line:|',
      'line:y|Recent ops',
      'line:|  • Law-Assistant — RAG legal research with citation verification',
      'line:|  • DarkVision    — 92% on low-light animal classification',
      'line:|  • AUTO-GRADER   — automated grading for a 100+ student class',
      'line:|  • QSide-Notebook — zero-install JupyterLite data viz',
    ],
  },
  '/about/looking-for.md': {
    type: 'file',
    kind: 'md',
    meta: 'intent',
    body: () => [
      'line:c|# looking-for',
      'line:|',
      'line:g|● ACTIVELY INTERVIEWING — Summer 2026 start',
      'line:|',
      'line:|  • Full-time MLE / AI Engineer roles',
      'line:|  • ML consulting engagements',
      'line:|  • Research collaborations in NLP, CV, or applied AI',
      'line:|',
      'line:dim|location :: East Lansing, MI · open to any US state · remote-ok',
      'line:dim|start    :: Summer 2026',
      'line:dim|contact  :: cd ../contact && cat info',
    ],
  },

  '/education': { type: 'dir', children: ['msu.md', 'icer-research.md'] },
  '/education/msu.md': {
    type: 'file',
    kind: 'md',
    meta: 'degree',
    body: () => [
      'line:c|# Michigan State University',
      'line:y|B.S. Computational Data Science  +  Mathematics minor',
      'line:dim|Aug 2022 — May 2026  ·  East Lansing, MI',
      'line:|',
      'line:|Coursework',
      'line:|  Deep Learning · Linear Algebra · Numerical Methods',
      'line:|  Algorithms     · Distributed Systems · Probability',
      "line:|  Real Analysis  · ODEs · Statistics",
      'line:|',
      "line:|Honors      :  Dean's List (multiple semesters)",
      'line:|Activities  :  iCER undergraduate research',
    ],
  },
  '/education/icer-research.md': {
    type: 'file',
    kind: 'md',
    meta: 'research',
    body: () => [
      'line:c|# iCER — Institute for Cyber-Enabled Research',
      'line:y|Undergraduate researcher',
      'line:dim|2024 — 2025 · MSU High-Performance Computing Center',
      'line:|',
      'line:|Co-authored an HPC agentic-AI framework that validates SLURM',
      'line:|batch-job scripts before they hit the queue — preventing the',
      'line:|cluster from running broken or wasteful jobs.',
      'line:|',
      'line:|Presented at iCER MidSURE 2025 (January 2025).',
    ],
  },

  '/experience': {
    type: 'dir',
    children: ['research-asst.md', 'auto-grader-ta.md', 'consulting.md'],
  },
  '/experience/research-asst.md': {
    type: 'file',
    kind: 'md',
    meta: 'role',
    body: () => [
      'line:c|# Undergraduate Research Assistant',
      'line:y|iCER · Michigan State University',
      'line:dim|2024 — 2025',
      'line:|',
      'line:|  • Co-designed an agentic-AI framework for validating SLURM',
      'line:|    job scripts. Catches misconfigs, GPU mismatches, bad',
      'line:|    partitions before submission.',
      'line:|  • Built the eval harness + dataset of broken scripts.',
      'line:|  • Presented at iCER MidSURE 2025.',
      'line:|',
      'line:dim|stack :: Python · LLM tool-use · SLURM · pytest',
    ],
  },
  '/experience/auto-grader-ta.md': {
    type: 'file',
    kind: 'md',
    meta: 'role',
    body: () => [
      'line:c|# AUTO-GRADER · TA tooling',
      'line:y|Computational Data Science · MSU',
      'line:dim|2023 — present',
      'line:|',
      'line:|  • Built an automated grading system that runs student',
      'line:|    submissions against unittest suites in sandboxed Linux',
      'line:|    environments. Used weekly by a 100+ student class.',
      'line:|  • Wrote graceful diff outputs so students see exactly',
      'line:|    which test failed and why.',
      'line:|',
      'line:dim|stack :: Python · unittest · Linux · bash · subprocess',
    ],
  },
  '/experience/consulting.md': {
    type: 'file',
    kind: 'md',
    meta: 'role',
    body: () => [
      'line:c|# Independent ML Consulting',
      'line:y|Self-employed',
      'line:dim|2024 — present',
      'line:|',
      'line:|Short engagements building RAG/LLM systems and CV models.',
      'line:|Comfortable with the whole loop: scoping, eval design,',
      'line:|training, deployment, and post-deploy monitoring.',
      'line:|',
      'line:dim|availability :: short-term · contract · remote',
    ],
  },

  '/projects': {
    type: 'dir',
    children: [
      'law-assistant.md',
      'darkvision.md',
      'auto-grader.md',
      'qside-notebook.md',
    ],
  },
  '/projects/law-assistant.md': {
    type: 'file',
    kind: 'md',
    meta: '★ flagship',
    body: () => [
      'line:c|# Law-Assistant  —  RAG research assistant',
      'line:y|FLAGSHIP · 2025 · v0.4.2 · open-source',
      'line:|',
      'line:|Hybrid retrieval (PostgreSQL full-text + Qdrant vector) over',
      'line:|legal corpora, served by a FastAPI backend with a Next.js',
      'line:|front. Generation runs on a local Llama 3.1 via Ollama.',
      'line:|',
      'line:|Every response passes through a citation-verification layer',
      'line:|that rejects claims not supported by retrieved evidence —',
      'line:|making hallucinations structurally impossible.',
      'line:|',
      'line:dim|stats',
      'line:|  chunks indexed     :  12,442',
      'line:|  retrieval mode     :  hybrid (FTS + dense)',
      'line:|  model              :  llama-3.1 (local via Ollama)',
      'line:|',
      'line:dim|stack :: Python · FastAPI · Next.js · PostgreSQL · Qdrant · Ollama',
      'line:|repo  :: link|https://github.com/michaelborek/Law-Assistant',
    ],
  },
  '/projects/darkvision.md': {
    type: 'file',
    kind: 'md',
    meta: 'CV',
    body: () => [
      'line:c|# DarkVision',
      'line:y|Computer-vision model · low-light animal classification',
      'line:|',
      'line:|Fine-tuned ResNet-18 with custom data augmentation for',
      'line:|darkness, motion blur, and IR-camera artifacts.',
      'line:|',
      'line:|Reached 92% accuracy on a held-out evaluation set, then',
      'line:|wrapped in a small inference service for batched scoring.',
      'line:|',
      'line:dim|stack :: PyTorch · ResNet-18 · OpenCV · numpy',
      'line:|repo  :: link|https://github.com/michaelborek/DarkVision',
    ],
  },
  '/projects/auto-grader.md': {
    type: 'file',
    kind: 'md',
    meta: 'tooling',
    body: () => [
      'line:c|# AUTO-GRADER',
      'line:y|Automated grading for 100+ student class',
      'line:|',
      'line:|Runs student submissions against unittest suites inside',
      'line:|sandboxed Linux environments. Produces instant feedback +',
      'line:|score with structured diff output.',
      'line:|',
      'line:dim|stack :: Python · unittest · Linux · subprocess',
      'line:|repo  :: link|https://github.com/michaelborek/AUTO-GRADER',
    ],
  },
  '/projects/qside-notebook.md': {
    type: 'file',
    kind: 'md',
    meta: 'data-viz',
    body: () => [
      'line:c|# QSide-Notebook',
      'line:y|Browser-based data viz · zero install',
      'line:|',
      'line:|Fully client-side JupyterLite with SQL + Python kernels for',
      'line:|exploring and charting datasets without setup.',
      'line:|',
      'line:dim|stack :: JupyterLite · Python · SQL',
      'line:|repo  :: link|https://github.com/michaelborek/QSide-Notebook',
      'line:|demo  :: link|https://malshaik.github.io/QSide-Notebook/',
    ],
  },

  '/publications': {
    type: 'dir',
    children: ['spie-medical-imaging.bib', 'icer-midsure-2025.bib'],
  },
  '/publications/spie-medical-imaging.bib': {
    type: 'file',
    kind: 'md',
    meta: 'peer-reviewed',
    body: () => [
      'line:c|@inproceedings{borek_spie_medical_imaging,',
      'line:|  author    = {Borek, M. et al.},',
      'line:|  title     = {Medical-Imaging Classification with',
      'line:|               Convolutional Neural Networks},',
      'line:y|  venue     = {SPIE Medical Imaging — proceedings},',
      'line:|  role      = {co-author},',
      'line:|  status    = {published · peer-reviewed},',
      'line:|}',
    ],
  },
  '/publications/icer-midsure-2025.bib': {
    type: 'file',
    kind: 'md',
    meta: 'presented',
    body: () => [
      'line:c|@misc{borek_icer_midsure_2025,',
      'line:|  author    = {Borek, M.},',
      'line:|  title     = {HPC Agentic-AI Framework for Batch Job',
      'line:|               Script Validation},',
      'line:y|  venue     = {iCER MidSURE 2025 — Michigan State University},',
      'line:|  date      = {January 2025},',
      'line:|  role      = {presenter · co-author},',
      'line:|}',
    ],
  },

  '/skills': {
    type: 'dir',
    children: ['ml.json', 'engineering.json', 'research.json'],
  },
  '/skills/ml.json': {
    type: 'file',
    kind: 'md',
    meta: 'ML / AI',
    body: () => [
      'line:c|# skills/ml',
      'line:|',
      'line:|skill:Python              :95',
      'line:|skill:PyTorch             :90',
      'line:|skill:RAG / LLMs          :90',
      'line:|skill:Pandas / NumPy      :95',
      'line:|skill:Computer Vision     :88',
      'line:|skill:scikit-learn        :85',
      'line:|skill:TensorFlow          :70',
    ],
  },
  '/skills/engineering.json': {
    type: 'file',
    kind: 'md',
    meta: 'eng',
    body: () => [
      'line:c|# skills/engineering',
      'line:|',
      'line:|skill:FastAPI             :88',
      'line:|skill:PostgreSQL          :82',
      'line:|skill:Qdrant / vector DB  :80',
      'line:|skill:Next.js / React     :80',
      'line:|skill:Docker / AWS        :70',
      'line:|skill:Git / CI-CD         :85',
    ],
  },
  '/skills/research.json': {
    type: 'file',
    kind: 'md',
    meta: 'research',
    body: () => [
      'line:c|# skills/research',
      'line:|',
      'line:|skill:Linux / HPC         :85',
      'line:|skill:SLURM batch         :80',
      'line:|skill:Ollama (local LLMs) :80',
      'line:|skill:JupyterLite / SQL   :82',
      'line:|skill:Technical writing   :78',
      'line:|skill:Lit review          :80',
    ],
  },

  '/contact': { type: 'dir', children: ['info', 'pgp.txt'] },
  '/contact/info': {
    type: 'file',
    kind: 'exe',
    meta: 'contact',
    body: () => [
      'line:c|# contact',
      'line:|',
      'line:|  email    : link|mailto:borekmi1@msu.edu|borekmi1@msu.edu',
      'line:|  github   : link|https://github.com/michaelborek|github.com/michaelborek',
      'line:|  linkedin : link|https://linkedin.com/in/michal-borek2003|linkedin.com/in/michal-borek2003',
      'line:|  location : East Lansing, MI · open to any US state',
      'line:|',
      'line:g|● status   : open_to_work · Summer 2026 start',
    ],
  },
  '/contact/pgp.txt': {
    type: 'file',
    kind: 'md',
    meta: 'keys',
    body: () => [
      'line:dim|-----BEGIN PGP PUBLIC KEY BLOCK-----',
      'line:dim|',
      'line:dim|(omitted — email me for the real one)',
      'line:dim|',
      'line:dim|-----END PGP PUBLIC KEY BLOCK-----',
    ],
  },
};

export const HOST = 'portfolio';
export const USER = 'michal';
