/**
 * Filesystem-style content for the terminal portfolio.
 * Lines use a tiny DSL: "line:<color-class>|<text>".
 *   - color-class: "", "c", "y", "g", "b", "m", "r", "o", "w", "dim", "faint"
 *   - special inline: "skill:Name:percent"  → rendered as a phosphor bar
 *   - special inline: "link|<url>|<label>" or "link|<url>"
 */

export type FsNode =
  | { type: 'dir'; children: string[] }
  | { type: 'file'; kind: 'md' | 'exe'; meta?: string; body: () => string[] };

export const FS: Record<string, FsNode> = {
  '/': {
    type: 'dir',
    children: [
      'README.md',
      'whoami',
      'about/',
      'education/',
      'experience/',
      'projects/',
      'publications/',
      'skills/',
      'leadership/',
      'contact/',
    ],
  },

  '/README.md': {
    type: 'file',
    kind: 'md',
    meta: 'welcome',
    body: () => [
      'line:c|# michal-borek/portfolio',
      'line:|',
      'line:|Most portfolios are landing pages. Mine boots.',
      'line:|',
      'line:dim|## getting around',
      'line:|',
      'line:|  ls                  list a directory',
      'line:|  cd <dir>            change directory',
      'line:|  cat <file>          read a file',
      'line:|  tree                show everything at once',
      'line:|  whoami              one-liner about me',
      'line:|  help                full command list',
      'line:|',
      'line:dim|## quick start',
      'line:|',
      'line:|  cd about && cat me.md          who I am',
      'line:|  cd experience && ls            where I have worked',
      'line:|  cd projects && ls              what I have shipped',
      'line:|  cat contact/info               how to reach me',
      'line:|',
      'line:dim|## prefer a document?',
      'line:|',
      'line:|  tap the "Document" toggle in the top-right corner.',
    ],
  },

  '/whoami': {
    type: 'file',
    kind: 'exe',
    meta: 'bio',
    body: () => [
      'line:w|Michal Borek',
      'line:dim|AI Engineer · Machine Learning & Quantitative Systems',
      'line:dim|MSU · B.S. Computational Data Science · Math minor · GPA 3.80',
      'line:dim|East Lansing, MI · open to any US state · grad May 2026',
    ],
  },

  '/about': { type: 'dir', children: ['me.md', 'looking-for.md'] },
  '/about/me.md': {
    type: 'file',
    kind: 'md',
    meta: 'bio',
    body: () => [
      'line:c|# Michal Borek',
      'line:|AI Engineer — Machine Learning & Quantitative Systems',
      'line:|',
      'line:|I build reliable AI systems, ML pipelines, and automation',
      'line:|tools for real-world workflows. Deep learning, LLM/RAG',
      'line:|applications, medical-imaging ML, HPC tooling, voice-AI',
      'line:|automation, and client-facing data science.',
      'line:|',
      'line:|Strong in Python, SQL, PyTorch, and backend development.',
      'line:|Comfortable translating ambiguous technical problems into',
      'line:|practical AI solutions with measurable impact.',
      'line:|',
      'line:|B.S. Computational Data Science at Michigan State, math',
      'line:|minor, graduating May 2026. GPA 3.80. Polish native,',
      'line:|English fluent.',
      'line:|',
      'line:y|Recent ops',
      'line:|  • AI Auto-Caller — Electron + OpenAI Realtime + Twilio',
      'line:|  • Legal RAG — citation-backed retrieval over legal docs',
      'line:|  • IQHSE — ordinal medical-image classification (chest X-ray)',
      'line:|  • iCER — SLURM job-script validator on Open OnDemand',
      'line:|  • Delta Dental capstone — project lead, canonical dataset',
    ],
  },
  '/about/looking-for.md': {
    type: 'file',
    kind: 'md',
    meta: 'intent',
    body: () => [
      'line:c|# looking-for',
      'line:|',
      'line:g|● ACTIVELY INTERVIEWING — Summer 2026 start',
      'line:|',
      'line:|  • Full-time AI / ML Engineer roles',
      'line:|  • Quantitative systems · applied research · LLM platforms',
      'line:|  • ML consulting engagements (short-term ok)',
      'line:|',
      'line:dim|location :: East Lansing, MI · open to any US state · remote-ok',
      'line:dim|start    :: Summer 2026',
      'line:dim|contact  :: cd ../contact && cat info',
    ],
  },

  '/education': { type: 'dir', children: ['msu.md'] },
  '/education/msu.md': {
    type: 'file',
    kind: 'md',
    meta: 'degree',
    body: () => [
      'line:c|# Michigan State University · College of Engineering',
      'line:y|B.S. Computational Data Science  ·  Minor in Mathematics',
      'line:dim|Aug 2022 — Expected May 2026  ·  East Lansing, MI',
      'line:|',
      'line:|GPA         :  3.80',
      'line:|',
      'line:|Coursework',
      'line:|  Deep Learning · Linear Algebra · Numerical Methods',
      'line:|  Algorithms     · Distributed Systems · Probability',
      "line:|  Real Analysis  · ODEs · Statistics",
      'line:|',
      "line:|Honors      :  Dean's List · 7 of 8 terms",
      'line:|              :  EGRID Silver Scholarship (2024)',
      'line:|              :  International Tuition Grant (2022)',
      'line:|              :  REHS Excellent Teamwork Award (2025)',
    ],
  },

  '/experience': {
    type: 'dir',
    children: ['iqhse-medical-imaging.md', 'icer-hpc-tooling.md'],
  },
  '/experience/iqhse-medical-imaging.md': {
    type: 'file',
    kind: 'md',
    meta: 'role · current',
    body: () => [
      'line:c|# Deep Learning Research Assistant · Medical Imaging ML',
      'line:y|Institute for Quantitative Health Science & Engineering · MSU',
      'line:dim|Nov 2023 — Present  ·  East Lansing, MI',
      'line:|',
      'line:|  • Built a modular PyTorch pipeline for ordinal medical',
      'line:|    image classification — reproducible data curation,',
      'line:|    training, evaluation, and automatic reporting.',
      'line:|  • Led hyperparameter optimization and model selection',
      'line:|    using held-out metrics, calibration analysis, and',
      'line:|    structured performance tracking.',
      'line:|  • Scaled training with PyTorch DDP on CUDA/SLURM —',
      'line:|    wall time 8 h → 3 h for large chest-X-ray runs.',
      'line:|  • Optimized preprocessing (image resizing + pipeline',
      'line:|    design) for large-scale chest X-ray experiments.',
      'line:|  • Supported clinical review with Captum-based saliency',
      'line:|    analysis to improve interpretability.',
      'line:|  • Disseminated through SPIE Medical Imaging 2025 and a',
      'line:|    Radiology: Artificial Intelligence manuscript under',
      'line:|    review.',
      'line:|',
      'line:dim|stack :: PyTorch · PyTorch DDP · CUDA · SLURM · Captum',
      'line:dim|         TorchXRayVision · scikit-learn · NumPy',
    ],
  },
  '/experience/icer-hpc-tooling.md': {
    type: 'file',
    kind: 'md',
    meta: 'role · current',
    body: () => [
      'line:c|# AI Engineer Intern · HPC / ML Tooling',
      'line:y|Institute for Cyber-Enabled Research · MSU',
      'line:dim|Jun 2023 — May 2026  ·  East Lansing, MI',
      'line:|',
      'line:|  • Shipped an AI-assisted SLURM job-script validator',
      'line:|    combining custom #SBATCH checks, ShellCheck, and a',
      'line:|    local-LLM review through Ollama — reduces submission',
      'line:|    errors and speeds user triage.',
      'line:|  • Deployed a Flask service + CLI on Open OnDemand with',
      'line:|    a live script editor, real-time analysis, and a',
      'line:|    SLURM-focused chat assistant for the HPCC community.',
      'line:|  • Designed policy-constrained LLM workflows with approved',
      'line:|    checks, controlled outputs, and validation logic to',
      'line:|    improve reliability and reduce unsupported guidance.',
      'line:|  • Authored an HPCC module for LM Studio — one-command',
      'line:|    LLM workflows under SLURM, local inference on H200s.',
      'line:|  • Presented the AI agent at Mid-SURE 2025 (live demo + Q&A).',
      'line:|  • Designed and delivered a Python training track for HPC',
      'line:|    users (fundamentals, OOP, NumPy, project structure).',
      'line:|',
      'line:dim|stack :: Python · Flask · Ollama · LM Studio · SLURM',
      'line:dim|         ShellCheck · Open OnDemand · Singularity · H200',
    ],
  },

  '/projects': {
    type: 'dir',
    children: [
      'ai-auto-caller.md',
      'legal-rag.md',
      'delta-dental-capstone.md',
      'darkvision.md',
      'auto-grader.md',
      'qside-notebook.md',
    ],
  },
  '/projects/ai-auto-caller.md': {
    type: 'file',
    kind: 'md',
    meta: '★ flagship · 2026',
    body: () => [
      'line:c|# AI Auto-Caller for Outbound Prospecting',
      'line:y|FLAGSHIP · Mar 2026 — present · shipping product',
      'line:|',
      'line:|Local macOS desktop app that automates outbound sales calls',
      'line:|using the OpenAI Realtime API and Twilio. One-click .dmg',
      'line:|with bundled ngrok — non-technical customers run it with',
      'line:|zero infra setup.',
      'line:|',
      'line:|  • Licensing + anti-piracy via a Cloudflare Worker',
      'line:|    kill-switch with HMAC-signed responses.',
      'line:|  • Validated against a Level-2 pentest — all 8 identified',
      'line:|    attack vectors closed.',
      'line:|  • Production release pipeline: 137 passing Python tests,',
      'line:|    automated release scripts, Nuitka-compiled ~60 MB',
      'line:|    engine binary.',
      'line:|',
      'line:dim|stack :: Electron · React · FastAPI · SQLite · OpenAI',
      'line:dim|         Realtime API · Twilio · Cloudflare Workers',
      'line:dim|         ngrok · Nuitka · HMAC',
    ],
  },
  '/projects/legal-rag.md': {
    type: 'file',
    kind: 'md',
    meta: 'RAG · 2026',
    body: () => [
      'line:c|# Legal Document Intelligence System',
      'line:y|End-to-end RAG · Dec 2025 — Feb 2026 · open-source',
      'line:|',
      'line:|RAG over PDF, DOCX, and TXT legal documents with',
      'line:|citation-backed answers. Hybrid retrieval over PostgreSQL',
      'line:|full-text search and Qdrant vectors, served by FastAPI,',
      'line:|generation on local Ollama inference.',
      'line:|',
      'line:|  • Structured outputs + verification / refusal logic.',
      'line:|  • Claim-to-source validation with excerpt generation.',
      'line:|  • Audit logging, retries, safe concurrency.',
      'line:|',
      'line:dim|stats',
      'line:|  chunks indexed     :  12,442',
      'line:|  retrieval mode     :  hybrid (FTS + dense)',
      'line:|  model              :  llama-3.1 (local via Ollama)',
      'line:|',
      'line:dim|stack :: Python · FastAPI · Next.js · PostgreSQL FTS',
      'line:dim|         Qdrant · Ollama · Llama 3.1',
      'line:|repo  :: link|https://github.com/michaelborek/Law-Assistant',
    ],
  },
  '/projects/delta-dental-capstone.md': {
    type: 'file',
    kind: 'md',
    meta: 'project lead · client',
    body: () => [
      'line:c|# Delta Dental Capstone — Project Lead',
      'line:y|Client-facing data science · Jan 2026 — Apr 2026',
      'line:|',
      'line:|Partner-sponsored data science capstone with the Delta',
      'line:|Dental Data Science Team. Coordinated scope, milestones,',
      'line:|working sessions, and stakeholder updates.',
      'line:|',
      'line:|  • Built a canonical dataset by consolidating source',
      'line:|    tables into a stable schema and data dictionary for',
      'line:|    downstream analytics.',
      'line:|  • Prototyped feature mapping into a 3D model to improve',
      'line:|    interpretability, visualization, and feature semantics.',
      'line:|',
      'line:dim|stack :: Python · Pandas · SQL · 3D viz · stakeholder mgmt',
    ],
  },
  '/projects/darkvision.md': {
    type: 'file',
    kind: 'md',
    meta: 'CV · side',
    body: () => [
      'line:c|# DarkVision',
      'line:y|Computer-vision side project · low-light animal classification',
      'line:|',
      'line:|Fine-tuned ResNet-18 with custom data augmentation for',
      'line:|darkness, motion blur, and IR-camera artifacts. Reached 92%',
      'line:|accuracy on a held-out evaluation set, wrapped in a small',
      'line:|inference service for batched scoring.',
      'line:|',
      'line:dim|stack :: PyTorch · ResNet-18 · OpenCV · NumPy',
      'line:|repo  :: link|https://github.com/michaelborek/DarkVision',
    ],
  },
  '/projects/auto-grader.md': {
    type: 'file',
    kind: 'md',
    meta: 'tooling · side',
    body: () => [
      'line:c|# AUTO-GRADER',
      'line:y|Automated grading for a 100+ student class',
      'line:|',
      'line:|Runs student submissions against unittest suites inside',
      'line:|sandboxed Linux environments. Produces instant feedback +',
      'line:|score with structured diff output.',
      'line:|',
      'line:dim|stack :: Python · unittest · Linux · subprocess',
      'line:|repo  :: link|https://github.com/michaelborek/AUTO-GRADER',
    ],
  },
  '/projects/qside-notebook.md': {
    type: 'file',
    kind: 'md',
    meta: 'data-viz · side',
    body: () => [
      'line:c|# QSide-Notebook',
      'line:y|Browser-based data viz · zero install',
      'line:|',
      'line:|Fully client-side JupyterLite with SQL + Python kernels for',
      'line:|exploring and charting datasets without setup.',
      'line:|',
      'line:dim|stack :: JupyterLite · Python · SQL',
      'line:|repo  :: link|https://github.com/michaelborek/QSide-Notebook',
      'line:|demo  :: link|https://malshaik.github.io/QSide-Notebook/',
    ],
  },

  '/publications': {
    type: 'dir',
    children: ['spie-pneumoconiosis-2025.bib', 'radiology-ai-2025.bib', 'icer-midsure-2025.bib'],
  },
  '/publications/spie-pneumoconiosis-2025.bib': {
    type: 'file',
    kind: 'md',
    meta: 'peer-reviewed · published',
    body: () => [
      'line:c|@inproceedings{liu_pneumoconiosis_spie_2025,',
      'line:|  author    = {Liu, M. and Loveless, I. and Huang, Z. and',
      'line:|               Borek, M. and Rosenman, K. and Alessio, A.',
      'line:|               and Wang, L.},',
      'line:|  title     = {Ordinal classification framework for',
      'line:|               multiclass grading of pneumoconiosis},',
      'line:y|  venue     = {SPIE Medical Imaging 2025: Computer-Aided',
      'line:y|               Diagnosis, 13407:134072Q},',
      'line:|  date      = {April 2025},',
      'line:|  doi       = link|https://doi.org/10.1117/12.3046353|10.1117/12.3046353',
      'line:|  status    = {published · peer-reviewed},',
      'line:|}',
    ],
  },
  '/publications/radiology-ai-2025.bib': {
    type: 'file',
    kind: 'md',
    meta: 'under review',
    body: () => [
      'line:c|@article{wang_pneumoconiosis_radiology_ai_2025,',
      'line:|  author    = {Wang, L. and Liu, M. and Huang, Z. and',
      'line:|               Loveless, I. and Borek, M. and Rosenman, K.',
      'line:|               and Alessio, A.},',
      'line:|  title     = {Pneumoconiosis Multi-task Screening and',
      'line:|               Classification using Fine-Tuned Deep',
      'line:|               Learning Models},',
      'line:y|  journal   = {Radiology: Artificial Intelligence},',
      'line:|  year      = {2025},',
      'line:|  status    = {under review},',
      'line:|}',
    ],
  },
  '/publications/icer-midsure-2025.bib': {
    type: 'file',
    kind: 'md',
    meta: 'presented',
    body: () => [
      'line:c|@misc{borek_icer_midsure_2025,',
      'line:|  author    = {Borek, M.},',
      'line:|  title     = {HPC Agentic-AI Framework for Batch Job',
      'line:|               Script Validation},',
      'line:y|  venue     = {Mid-SURE 2025 · Michigan State University},',
      'line:|  date      = {Summer 2025},',
      'line:|  role      = {presenter},',
      'line:|}',
    ],
  },

  '/skills': {
    type: 'dir',
    children: [
      'languages.json',
      'ai-ml.json',
      'llm-rag.json',
      'backend.json',
      'product-automation.json',
      'hpc-distributed.json',
    ],
  },
  '/skills/languages.json': {
    type: 'file',
    kind: 'md',
    meta: 'languages',
    body: () => [
      'line:c|# skills/languages',
      'line:|',
      'line:|skill:Python              :95',
      'line:|skill:SQL                 :88',
      'line:|skill:C++                 :75',
      'line:|skill:Bash                :82',
      'line:dim|Spoken: Polish (native) · English (fluent)',
    ],
  },
  '/skills/ai-ml.json': {
    type: 'file',
    kind: 'md',
    meta: 'AI / ML',
    body: () => [
      'line:c|# skills/ai-ml',
      'line:|',
      'line:|skill:PyTorch             :92',
      'line:|skill:PyTorch DDP / CUDA  :85',
      'line:|skill:scikit-learn        :88',
      'line:|skill:TorchXRayVision     :80',
      'line:|skill:Captum (saliency)   :78',
      'line:|skill:Pandas / NumPy      :95',
      'line:|skill:Model eval / calib. :88',
      'line:|skill:Hyperparam tuning   :85',
    ],
  },
  '/skills/llm-rag.json': {
    type: 'file',
    kind: 'md',
    meta: 'LLM / RAG',
    body: () => [
      'line:c|# skills/llm-rag',
      'line:|',
      'line:|skill:OpenAI Realtime API :90',
      'line:|skill:Ollama (local LLMs) :88',
      'line:|skill:Qdrant / vector DB  :85',
      'line:|skill:Postgres FTS        :82',
      'line:|skill:Citation-backed RAG :90',
      'line:|skill:Structured outputs  :88',
      'line:|skill:Verification/refusal:85',
    ],
  },
  '/skills/backend.json': {
    type: 'file',
    kind: 'md',
    meta: 'backend / systems',
    body: () => [
      'line:c|# skills/backend',
      'line:|',
      'line:|skill:FastAPI             :90',
      'line:|skill:Flask               :85',
      'line:|skill:Docker              :80',
      'line:|skill:REST APIs           :88',
      'line:|skill:Git                 :92',
      'line:|skill:Linux               :88',
      'line:|skill:SQLite              :82',
    ],
  },
  '/skills/product-automation.json': {
    type: 'file',
    kind: 'md',
    meta: 'product / automation',
    body: () => [
      'line:c|# skills/product-automation',
      'line:|',
      'line:|skill:Electron            :82',
      'line:|skill:React               :82',
      'line:|skill:Twilio              :80',
      'line:|skill:Cloudflare Workers  :78',
      'line:|skill:ngrok               :80',
      'line:|skill:Nuitka              :75',
      'line:|skill:ShellCheck          :78',
      'line:|skill:Jupyter             :88',
    ],
  },
  '/skills/hpc-distributed.json': {
    type: 'file',
    kind: 'md',
    meta: 'HPC / distributed',
    body: () => [
      'line:c|# skills/hpc-distributed',
      'line:|',
      'line:|skill:SLURM               :88',
      'line:|skill:CUDA                :82',
      'line:|skill:PyTorch DDP         :85',
      'line:|skill:Singularity         :78',
      'line:|skill:MSU HPCC            :88',
      'line:|skill:Open OnDemand       :80',
    ],
  },

  '/leadership': {
    type: 'dir',
    children: ['resident-assistant.md', 'polish-club.md', 'awards.md'],
  },
  '/leadership/resident-assistant.md': {
    type: 'file',
    kind: 'md',
    meta: 'leadership',
    body: () => [
      'line:c|# Resident Assistant',
      'line:y|MSU Housing & Residence Education',
      'line:dim|Aug 2024 — May 2026 · East Lansing, MI',
      'line:|',
      'line:|Supported 100+ residents through mentoring, conflict',
      'line:|mediation, incident response, and community programming.',
      'line:|',
      'line:g|● Recognized with the REHS Excellent Teamwork Award (2025).',
    ],
  },
  '/leadership/polish-club.md': {
    type: 'file',
    kind: 'md',
    meta: 'co-founder',
    body: () => [
      'line:c|# Polish Club, Michigan State University',
      'line:y|Co-Founder · Executive Board Member',
      'line:dim|Oct 2024 — May 2026',
      'line:|',
      'line:|Co-founded a student organization supporting Polish',
      'line:|culture, student community, campus engagement, outreach,',
      'line:|and event planning.',
    ],
  },
  '/leadership/awards.md': {
    type: 'file',
    kind: 'md',
    meta: 'awards',
    body: () => [
      'line:c|# Awards',
      'line:|',
      'line:y|● REHS Excellent Teamwork Award',
      'line:dim|  MSU Residence Education & Housing Services · 2025',
      'line:|',
      "line:y|● Dean's List",
      'line:dim|  Michigan State University · 7 of 8 terms',
      'line:|',
      'line:y|● EGRID Silver Scholarship',
      'line:dim|  Michigan State University · 2024',
      'line:|',
      'line:y|● International Tuition Grant',
      'line:dim|  Michigan State University · 2022',
    ],
  },

  '/contact': { type: 'dir', children: ['info', 'pgp.txt'] },
  '/contact/info': {
    type: 'file',
    kind: 'exe',
    meta: 'contact',
    body: () => [
      'line:c|# contact',
      'line:|',
      'line:|  email    : link|mailto:borekmi1@msu.edu|borekmi1@msu.edu',
      'line:|  phone    : (517) 980-3231',
      'line:|  github   : link|https://github.com/michaelborek|github.com/michaelborek',
      'line:|  linkedin : link|https://linkedin.com/in/michal-borek2003|linkedin.com/in/michal-borek2003',
      'line:|  location : East Lansing, MI · open to any US state',
      'line:|  spoken   : Polish (native) · English (fluent)',
      'line:|',
      'line:g|● status   : open_to_work · Summer 2026 start',
    ],
  },
  '/contact/pgp.txt': {
    type: 'file',
    kind: 'md',
    meta: 'keys',
    body: () => [
      'line:dim|-----BEGIN PGP PUBLIC KEY BLOCK-----',
      'line:dim|',
      'line:dim|(omitted — email me for the real one)',
      'line:dim|',
      'line:dim|-----END PGP PUBLIC KEY BLOCK-----',
    ],
  },
};

export const HOST = 'portfolio';
export const USER = 'michal';
